"""Corregimos la columna de lastname en users, el tipo de datos que recibía era incorrecto

Revision ID: 6f7428633fd9
Revises: 
Create Date: 2024-09-06 10:28:02.040628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7428633fd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),  # Ajusta la longitud según tus necesidades
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###